### ISSUE TITLE
请问大佬这个sql可以给全一点嘛

### ISSUE THREAD

**Issue by qiu-q** [Zddu/monitorsys-vue#22]

**Comment by Zddu** [comment]
这个项目已经没再维护了 之前的sql没做保留，另外开了一个新项目，最近在做。https://gitee.com/zdde/cool-network-system

**Comment by qiu-q** [comment]
感谢大佬的回复 谢谢大佬






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月1日(星期二) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zddu/monitorsys-vue] 请问大佬这个sql可以给全一点嘛 (Issue #22)





 
这个项目已经没再维护了 之前的sql没做保留，另外开了一个新项目，最近在做。https://gitee.com/zdde/cool-network-system
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
